name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Adjust this to the Node.js version you're using

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run tests (assuming you have tests in your project)
    - name: Run tests
      run: npm test
    
    # Build the project (if applicable, though for backend Node.js, this might not be necessary)
    - name: Build the project
      run: npm run build
